### ISSUE TITLE
You broke Frame carriages. They have a different ID.

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#115]
When I noticed after starting a new test world, I load up another one.

No idea if it's related. I'll omit all the trash in the crash report, as you can trust I know my shit.

Time: 3/5/15 1:40 PM
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at me.planetguy.remaininmotion.Closeables.getCloseable(Closeables.java:31)
	at me.planetguy.remaininmotion.util.MultiTypeCarriageUtil.fillFramePackage(MultiTypeCarriageUtil.java:46)
	at me.planetguy.remaininmotion.FrameCarriageMatchers$1$1.fillPackage(FrameCarriageMatchers.java:39)
	at me.planetguy.remaininmotion.util.MultiTypeCarriageUtil.fillPackage(MultiTypeCarriageUtil.java:21)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageEngine.GeneratePackage(TileEntityCarriageEngine.java:21)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.prepareDefaultPackage(TileEntityCarriageDrive.java:316)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.PreparePackage(TileEntityCarriageDrive.java:270)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.func_145845_h(TileEntityCarriageDrive.java:244)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at me.planetguy.remaininmotion.Closeables.getCloseable(Closeables.java:31)
	at me.planetguy.remaininmotion.util.MultiTypeCarriageUtil.fillFramePackage(MultiTypeCarriageUtil.java:46)
	at me.planetguy.remaininmotion.FrameCarriageMatchers$1$1.fillPackage(FrameCarriageMatchers.java:39)
	at me.planetguy.remaininmotion.util.MultiTypeCarriageUtil.fillPackage(MultiTypeCarriageUtil.java:21)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageEngine.GeneratePackage(TileEntityCarriageEngine.java:21)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.prepareDefaultPackage(TileEntityCarriageDrive.java:316)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.PreparePackage(TileEntityCarriageDrive.java:270)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.func_145845_h(TileEntityCarriageDrive.java:244)

-- Block entity being ticked --
Details:
	Name: JAKJ_RedstoneInMotion_CarriageEngineEntity // me.planetguy.remaininmotion.drive.TileEntityCarriageEngine
	Block type: ID #865 (tile.JAKJ_RedstoneInMotion_CarriageDrive // me.planetguy.remaininmotion.drive.BlockCarriageDrive)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-348,70,3308), Chunk: (at 4,4,12 in -22,206; contains blocks -352,0,3296 to -337,255,3311), Region: (-1,6; contains chunks -32,192 to -1,223, blocks -512,0,3072 to -1,255,3583)
	Actual block type: ID #865 (tile.JAKJ_RedstoneInMotion_CarriageDrive // me.planetguy.remaininmotion.drive.BlockCarriageDrive)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by da3dsoul** [comment]
Ok...you broke all carriages.

**Comment by da3dsoul** [comment]
Well, for now I commented out the recipe and BlockCarriage changes.

**Comment by planetguy32** [comment]
I couldn't replicate this. Maybe I left the code in an intermediate broken state earlier?

The simple frame carriage was originally intended to be a crafting ingredient which would be picked up by other mods like Buildcraft or ForgeMultipart to be made into frame covers. It therefore has to be obtainable in survival mode, and to prevent everyone complaining that their frames don't work I tried to make them behave like a frame carriage as best I could.

**Comment by da3dsoul** [comment]
Try in a test world, after uncommenting out the stuff commented in https://github.com/planetguy32/RemainInMotion/commit/a683536da270a602d4fecbc346d6083e29c09be6

**Comment by planetguy32** [comment]
I couldn't replicate this in my default setup, or on Java 8. The stuff you commented out there should be only creative tab and crafting, not related to gameplay.

**Comment by da3dsoul** [comment]
Yeah it was elsewhere. I fixed it working on something else.

**Comment by da3dsoul** [comment]
It did happen in the same commit I referenced, though.

**Comment by da3dsoul** [comment]
You broke it again.
In this line:

for (int i=1; i<Types.values().length; i++) {

You are preventing the old frame carriages from being initialized.

You also made the new ones not camouflagable.

**Comment by da3dsoul** [comment]
In BlockCarriage.java

**Comment by da3dsoul** [comment]
The recipes also make it impossible or very difficult to get the normal frames.

**Comment by planetguy32** [comment]
That doesn't initialize anything, it only adds items to the creative tab. 

The old frames are intentionally hard to obtain, because you're intended to use the simple frames whenever possible. Old frames are automatically converted into heavyweight frames whenever necessary (that is, when a side is closed with a screwdriver or when you craft decorated versions) and are converted back when you mine them (if they aren't decorated - then they stay as old frame items to keep their decoration).

I tested it and the new ones may be camouflaged - the recipe produces an old frame stack, since new frames don't understand camouflage.

**Comment by da3dsoul** [comment]
Hmmmm...I'll look at it a bit further.

**Comment by da3dsoul** [comment]
I see...interesting and very well done.

**Comment by planetguy32** [comment]
Sorry for not making this clear to you earlier.
