### ISSUE TITLE
Error when moving tesseract

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#128]
It doesn't crash or stop working, but it happens.

[06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassCastException: me.planetguy.remaininmotion.spectre.TileEntitySupportiveSpectre cannot be cast to cofh.api.tileentity.IRedstoneControl [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.thermalexpansion.network.PacketTEBase.handlePacket(PacketTEBase.java:36) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:364) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:98) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.main.Main.main(SourceFile:148) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at java.lang.reflect.Method.invoke(Method.java:606) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [06:48:22] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [06:48:27] [Client thread/ERROR] [ThermalExpansion]: Packet payload failure! Please check your config files! [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassCastException: me.planetguy.remaininmotion.spectre.TileEntitySupportiveSpectre cannot be cast to cofh.api.tileentity.IRedstoneControl [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.thermalexpansion.network.PacketTEBase.handlePacket(PacketTEBase.java:36) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:364) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:98) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.main.Main.main(SourceFile:148) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at java.lang.reflect.Method.invoke(Method.java:606) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [06:48:27] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [06:51:30] [Client thread/ERROR] [ThermalExpansion]: Packet payload failure! Please check your config files! [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassCastException: me.planetguy.remaininmotion.spectre.TileEntitySupportiveSpectre cannot be cast to cofh.api.tileentity.IRedstoneControl [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.thermalexpansion.network.PacketTEBase.handlePacket(PacketTEBase.java:36) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:364) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:98) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.main.Main.main(SourceFile:148) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at java.lang.reflect.Method.invoke(Method.java:606) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [06:51:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [06:54:30] [Client thread/ERROR] [ThermalExpansion]: Packet payload failure! Please check your config files! [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.thermalexpansion.network.PacketTEBase.handlePacket(PacketTEBase.java:37) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:364) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:98) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.main.Main.main(SourceFile:148) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at java.lang.reflect.Method.invoke(Method.java:606) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at me.planetguy.remaininmotion.network.RenderPacket.Handle(RenderPacket.java:97) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at me.planetguy.remaininmotion.network.Message.onMessage(Message.java:33) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at me.planetguy.remaininmotion.network.Message.onMessage(Message.java:15) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.main.Main.main(SourceFile:148) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at java.lang.reflect.Method.invoke(Method.java:606) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [06:54:30] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [06:54:33] [Client thread/ERROR] [ThermalExpansion]: Packet payload failure! Please check your config files! [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.thermalexpansion.network.PacketTEBase.handlePacket(PacketTEBase.java:37) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketCoFHBase.handleClientSide(PacketCoFHBase.java:364) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:98) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cofh.core.network.PacketHandler.decode(PacketHandler.java:40) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.client.main.Main.main(SourceFile:148) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at java.lang.reflect.Method.invoke(Method.java:606) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [06:54:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by planetguy32** [comment]
I'm having trouble reproducing this. Which mod versions are involved? What does your build look like?

**Comment by da3dsoul** [comment]
latest of all P:R and RemainInMotion. http://i58.tinypic.com/6r1o29.png is my setup.

**Comment by da3dsoul** [comment]
Primarily for clients on a LAN server

**Comment by da3dsoul** [comment]
I posted those on the wrong issue. Nonetheless the same for CoFH

**Comment by da3dsoul** [comment]
Also I have the tesseract set to only receive energy and ignore Redstone

**Comment by planetguy32** [comment]
I think this might be that Thermal Expansion's server->client description packet arrived after RemIM had already set up spectres there, so the cast to the description's relevant tile entity is actually unsafe. Packet reordering is quite rare, so it's probably pretty hard to reproduce this. I'll mention this on the CoFH issue tracker.

**Comment by planetguy32** [comment]
Can you replicate this with the fix for #130 implemented?

**Comment by da3dsoul** [comment]
I'll try

**Comment by da3dsoul** [comment]
I haven't seen it since so I'll say it's fixed.
