### ISSUE TITLE
NPE on FMP Send Description Packet

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#129]
145) [?:1.7.0_45] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_45] at java.lang.Thread.run(Thread.java:744) [?:1.7.0_45] [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at codechicken.multipart.MultipartHelper$.sendDescPacket(MultipartHelper.scala:49) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at codechicken.multipart.MultipartHelper.sendDescPacket(MultipartHelper.scala) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at e.planetguy.remaininmotion.core.interop.fmp.EventHandlerFMP.onPlaced(EventHandlerFMP.java:73) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.eventhandler.ASMEventHandler_285_EventHandlerFMP_onPlaced_TEPostPlaceEvent.invoke(.dynamic) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at me.planetguy.remaininmotion.spectre.TileEntityMotiveSpectre.constructTE(TileEntityMotiveSpectre.java:237) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at me.planetguy.remaininmotion.spectre.TileEntityMotiveSpectre.doRelease(TileEntityMotiveSpectre.java:151) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at me.planetguy.remaininmotion.spectre.TileEntityMotiveSpectre.Release(TileEntityMotiveSpectre.java:122) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at me.planetguy.remaininmotion.spectre.TileEntityMotiveSpectre.func_145845_h(TileEntityMotiveSpectre.java:97) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.world.World.func_72939_s(World.java:1939) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [06:54:24] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by da3dsoul** [comment]
This kicks clients but otherwise continues working

**Comment by planetguy32** [comment]
The cause of this is a null TileEntity being passed into FMP. Maybe it was because the TE is still registered for ticks in the world, in which case the fix #130 probably fixes it.

**Comment by da3dsoul** [comment]
I haven't seen it since, so I'll say it's fixed.

**Comment by planetguy32** [comment]
In #136 this had something to do with chunk unloading... I'll see if I can reproduce it.

**Comment by planetguy32** [comment]
I think I fixed this, but could you please test it if you have time? It's a pretty big bug, so I'd like to release it as soon as possible, but it would be a nuisance for everyone if it doesn't work properly.

**Comment by da3dsoul** [comment]
I accidentally deleted this in a merge. Back in https://github.com/planetguy32/RemainInMotion/commit/67e9873b32cd9f8aaa3039599c0b68987d597b72
