### ISSUE TITLE
Crash when moving simple engine + lever without Buildcraft

### ISSUE THREAD

**Issue by VeriTi** [planetguy32/RemainInMotion#143]
Time: 28.04.15 21:08
Description: Ticking block entity

java.lang.NoClassDefFoundError: buildcraft/factory/BlockTank
	at me.planetguy.remaininmotion.core.interop.EventHandlerDebugInspector.filter(EventHandlerDebugInspector.java:22)
	at me.planetguy.remaininmotion.core.interop.EventHandlerDebugInspector.onBlockSelectForMoveEvent(EventHandlerDebugInspector.java:32)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_403_EventHandlerDebugInspector_onBlockSelectForMoveEvent_BlockSelectForMoveEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at me.planetguy.remaininmotion.motion.CarriagePackage.AddBlock(CarriagePackage.java:126)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageEngine.GeneratePackage(TileEntityCarriageEngine.java:15)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.prepareDefaultPackage(TileEntityCarriageDrive.java:369)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.PreparePackage(TileEntityCarriageDrive.java:323)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.func_145845_h(TileEntityCarriageDrive.java:294)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: buildcraft.factory.BlockTank
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more
Caused by: java.lang.NullPointerException

Full crash log: https://gist.github.com/VeriTi/10a306b0af8ddb1f9c65

**Comment by planetguy32** [comment]
Sorry about that. You should be fine on v2.6.1.2.
