### ISSUE TITLE
Crash when activating a carriage in SMP due to server trying to load client-side rendering code

### ISSUE THREAD

**Issue by SargeRyong** [planetguy32/RemainInMotion#173]
Occurs when activating a carriage motor on a server, causing a server crash.

Looks to be trying to call client-side rendering code for some reason?

java.lang.NoClassDefFoundError: me/planetguy/remaininmotion/api/event/PreRenderDuringMovementEvent
	at me.planetguy.remaininmotion.motion.CarriagePackage.AddBlock_impl(CarriagePackage.java:131)
	at me.planetguy.remaininmotion.motion.CarriagePackage.AddBlock(CarriagePackage.java:95)
	at me.planetguy.remaininmotion.carriage.TileEntityStructureCarriage.fillPackage(TileEntityStructureCarriage.java:339)
	at me.planetguy.remaininmotion.carriage.TileEntityStructureCarriage.fillPackage(TileEntityStructureCarriage.java:257)
	at me.planetguy.remaininmotion.util.MultiTypeCarriageUtil.fillPackage(MultiTypeCarriageUtil.java:21)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageEngine.GeneratePackage(TileEntityCarriageEngine.java:37)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.prepareDefaultPackage(TileEntityCarriageDrive.java:388)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.PreparePackage(TileEntityCarriageDrive.java:342)
	at me.planetguy.remaininmotion.drive.TileEntityCarriageDrive.func_145845_h(TileEntityCarriageDrive.java:313)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: me.planetguy.remaininmotion.api.event.PreRenderDuringMovementEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: java.lang.RuntimeException: Attempted to load class me/planetguy/remaininmotion/api/event/PreRenderDuringMovementEvent for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 18 more

**Comment by SargeRyong** [comment]
Neglected to mention - this is on RemainInMotion 2.8.5.

**Comment by planetguy32** [comment]
...Dammit.

**Comment by SargeRyong** [comment]
Awesome, thanks for the quick response.

**Comment by planetguy32** [comment]
Fixed with eb12caa9675d194f756de77a6a5db1e23c709869
