### ISSUE TITLE
Carpenter's Blocks crashes when moving down

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#179]

**Comment by da3dsoul** [comment]
I hit the wrong button. Anyway, it doesn't happen consistently, but there is a ClassCastException that casts air to BlockCoverable. I'll post more detail when it happens again.

**Comment by da3dsoul** [comment]
Yes, it only happens when moving down, moving up or sideways is fine.

**Comment by da3dsoul** [comment]
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to com.carpentersblocks.block.BlockCoverable
at com.carpentersblocks.tileentity.TEBase.onDataPacket(TEBase.java:142)
at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1144)
at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by da3dsoul** [comment]
NVM, it was on their end and it is fixed.
